### ISSUE TITLE
gmpy2

### ISSUE THREAD

**Issue by videlec** [videlec/pplpy#1]
We want to use [gmpy2](https://github.com/aleaxit/gmpy) for integers and rationals.

- [x] how to construct gmpy types from C and Cython. If needed, provide the relevant pull requests to the gmpy2 project (see also [issue 121](https://github.com/aleaxit/gmpy/issues/121)).
- [x] set gmpy2 as a dependency in setup.py
- [x] replace the module cygmp by gmpy2
- [x] pplpy output gmpy2 objects
- [x] get rid of `mpz_set_pylong` (should either be part of gmpy2 or used via `GMPy_MPZ_From_PyIntOrLong`)
- [x] get rid of `gmpy2_wrap.[pyx|pxd]` (would better be part of `gmpy2`): see [PR 137 in gmpy2](https://github.com/aleaxit/gmpy/pull/137)
- [x] find a solution for [issue 132](https://github.com/aleaxit/gmpy/issues/132) that makes Travis-CI unhappy
- [x] setup.py should not require the presence of gmpy2 (it does right now to find the appropriate path for headers): : see [PR 137 in gmpy2](https://github.com/aleaxit/gmpy/pull/137)
- [x] update the README for installation on ubuntu. There is no indication how to install `cysignals` or `gmpy2`

**Comment by vinklein** [comment]
The selected solution is to use gmpy2

**Comment by vinklein** [comment]
checkbox "implement in Sage conversion from and to gmpy2 (trac ticket XXX)" removed, it's rather a part of issue #12

**Comment by vinklein** [comment]
You can have travis work with ubuntu 14.04 by adding the two line below
"dist: trusty
sudo: required" to travis.yml

**Comment by vinklein** [comment]
README.rst should be updated again after [gmpy2](https://github.com/aleaxit/gmpy) next release.
pip install git+https://github.com/aleaxit/gmpy => pip install gmpy2
