### ISSUE TITLE
Create a new version of pplpy on pypi.python.org and pythonhosted.org 

### ISSUE THREAD

**Issue by vinklein** [videlec/pplpy#10]
https://gitlab.com/videlec/pplpy/issues/6

**Comment by jesusjda** [comment]
Please update pplpy on pypi.python.org and pythonhosted.org to the actual version on github

**Comment by videlec** [comment]
@jesusjda what do you need which is not in the pypi version? We are waiting the next release of [gmpy2](https://github.com/aleaxit/gmpy) (see in particuliar [their issue 146](https://github.com/aleaxit/gmpy/issues/146)). As soon as gmpy2 is released, pplpy will follow.

In the mean time you can use the development version by doing
```
$ pip install git+https://github.com/aleaxit/gmpy
$ pip install git+https://github.com/videlec/pplpy
```

**Comment by jesusjda** [comment]
Thanks! I was interested in python 3 compatibility your issue #5

**Comment by videlec** [comment]
@jesusjda version 0.7 is available on pypi

**Comment by jesusjda** [comment]
Thank you for let me know! 

But, I'm working with my fork in order to add all the methods that I need.. I will make a PR when everything is ready and stable.
