### ISSUE TITLE
Improve code readability by splitting it in several files

### ISSUE THREAD

**Issue by vinklein** [videlec/pplpy#11]
Split wrapper.pyx into several files. Like in ppl, objects like MIP_Problem or Polyhedron should have their own file

 - [x] add header with copyright
 - [x] clean history (non working commits)
 - [x] avoid increase of library size -> #15

**Comment by vinklein** [comment]
New classes/Files repartition :
wrappers.pyx	
- Variable
- Linear_Expression
- Poly_Gen_Relation
- Poly_Con_Relation

mip_problem.pyx
- MIP_Problem
- MIP_Problem_constraints_iterator

polyhedron.pyx
- Polyhedron
- C_Polyhedron
- NNC_Polyhedron

generator.pyx
- Generator
- Generator_System
- Generator_System_iterator

constraint.pyx
- Constraint
- Constraint_System
- Constraint_System_iterator

**Comment by videlec** [comment]
Better remove wrappers.pyx/wrappers.pxd!

**Comment by vinklein** [comment]
Repartition updated :
linear_algebra.pyx

    Variable
    Linear_Expression

mip_problem.pyx

    MIP_Problem
    MIP_Problem_constraints_iterator

polyhedron.pyx

    Polyhedron
    C_Polyhedron
    NNC_Polyhedron

generator.pyx

    Generator
    Generator_System
    Generator_System_iterator
    Poly_Gen_Relation


constraint.pyx

    Constraint
    Constraint_System
    Constraint_System_iterator
    Poly_Con_Relation

**Comment by videlec** [comment]
You have ugly commit messages on your master branch

    commit 8bfef00745c276f2cf7eb438cbedc6c3e287b35a
    Author: vklein <vklein@labri.fr>
    Date:   Wed Mar 22 16:22:30 2017 +0100

        Dev in progress
        Update ppl.mip_problem sources :
        sources=['ppl/mip_problem.pyx'], => sources=['ppl/mip_problem.pyx', 'ppl/ppl_shim.cc']

    commit c05caae7de57045ac61e182a5287cd2583a76aa7
    Author: vklein <vklein@labri.fr>
    Date:   Wed Mar 22 10:54:17 2017 +0100

        Dev & test in progress
        - remove duplicate def of _wrap_Generator

    commit 24accb18a38f1a0dbcff7146223270d3c3ab327d
    Author: Vincent Klein <vinklein@gmail.com>
    Date:   Tue Mar 21 10:07:50 2017 +0100

        Warn ! This commit doesn't compile, dev in progress.
        Split wrappers.pyx in several files

**Comment by videlec** [comment]
Each pyx file should start with a proper header with license and copyright

**Comment by videlec** [comment]
As a consequence of this splitting the pplpy library is now twice bigger

Before

    $ du -sh ~/.local/lib/python3.6/site-packages/ppl
    3,5M    /home/vincent/.local/lib/python3.6/site-packages/ppl

After

    $ du -sh ~/.local/lib/python3.6/site-packages/ppl
    6,5M    /home/vincent/.local/lib/python3.6/site-packages/ppl
