### ISSUE TITLE
Sage integration

### ISSUE THREAD

**Issue by videlec** [videlec/pplpy#12]
https://gitlab.com/videlec/pplpy/issues/5

**Comment by vinklein** [comment]
Adapt the Sage code to deal with gmpy2 objects => see trac [22928](https://trac.sagemath.org/ticket/22928)

**Comment by vinklein** [comment]
check "see if anybody changed sage/libs/ppl.pyx since the fork (if yes, list the commit and port them into pplpy)" #20
