### ISSUE TITLE
also test on osx

### ISSUE THREAD

**Issue by videlec** [videlec/pplpy#22]
Travis CI can also [run tests on OS X](https://docs.travis-ci.com/user/multi-os/).

**Comment by vinklein** [comment]
Basically OSX with Travis CI doesn't support python (https://travis-ci.org/vinklein/pplpy/builds/242032726).

I tried to adapt some workaround to meet our needs (https://github.com/HealthCatalyst/healthcareai-r/issues/401)

**Comment by vinklein** [comment]
Workaround found. Take note that with tests on OSX, Travis CI tests are way longer than before (35 min).
