### ISSUE TITLE
Support Polyhedron widening

### ISSUE THREAD

**Issue by jesusjda** [videlec/pplpy#25]
I want to extend your wrapper by adding the widening methods for Polyhedron as PPL already has.

I [forked your repo](https://github.com/jesusjda/pplpy) and tried to add it, but I don't know how Cython works. I cannot add the `unsigned * tp` parameter

Are you planing to add the widening?

**Comment by videlec** [comment]
Where is the `unsigned` type defined? Is it a typedef from PPL?

**Comment by videlec** [comment]
Sorry, `unsigned` is just the C type `unsigned int`. Pointers are not handled by Cython in declaration of Python functions (because there is no corresponding types in Python). Do you know why PPL implements these functions with pointers `unsigned *` instead of `unsigned`? Could you provide some examples using the `tp` argument?

**Comment by jesusjda** [comment]
As I understand [here](http://bugseng.com/products/ppl/documentation/user/ppl-user-1.2-html/index.html#Widening_with_Tokens) is a positive integer which the widening methods will decrement until it reaches the value 0.

So, it has to be pointer to allow the widening methods to decrease it..

I will look for examples this week.

**Comment by videlec** [comment]
But from the user point of view, is it useful to use pointer instead of plain `unsigned`? If it does not, you can simply do something like
```
def my_widening_method(self, Polyhedron y, unsigned tp=0):
    self.thisptr.widening_assign(y.thisptr[0], &tp)
```
which should succeed in Cython.

**Comment by jesusjda** [comment]
Here is an [example](https://gist.github.com/jesusjda/f59384471e4771b8b7ada3ac84df6d5b) where you can see how the `tp` parameter works. The method modify the value of the unsigned for future iterations or calls. 

I have some ideas to reproduce this, but I'm not sure if one of them is able to be release in your wrapper.

1. Create a type who wraps the integer.
2. Return the new value of tp.
3. Ignore the parameter (always use the default value '=0').

**Comment by videlec** [comment]
Is this a realistic usage? The exact same function is called twice with the exact same arguments.
```
ph1.H79_widening_assign(ph2,&tp);   /* line 64 */
ph1.H79_widening_assign(ph2,&tp);   /* line 75 */
```
Could you answer my second comment?

**Comment by jesusjda** [comment]
It is realistic if you think it could be in a loop. For me, it is not needed.. 

about your second comment,
I don't think it is really useful, the parameter is used to delay the application of the widening, you can control it outside with any effort.. 

I just wanted to be as closer to C++ as I can

**Comment by videlec** [comment]
I understand. Concerning your propositions I will not accept 1 but will be fully satisfied with 2 or 3.

If you create a pull request, I will merge it (provided the tests pass).

**Comment by jesusjda** [comment]
PR #26 done!
Thanks for all!

**Comment by videlec** [comment]
PR #26 is merged. Thanks.
