### ISSUE TITLE
LinearExpression core dump with sage.

### ISSUE THREAD

**Issue by vinklein** [videlec/pplpy#27]
On sage this code:
```
sage: from ppl import Linear_Expression
sage: Linear_Expression((1/2, 1), 0)
```
provoke a segfault. It may be a sig_on / sig_off missing.

This error appear with ppl_lattice_polytope.py's doctest :
```
sage: from sage.geometry.polyhedron.ppl_lattice_polytope import LatticePolytope_PPL
sage: LatticePolytope_PPL((0,0),(1/2,1))
Traceback (most recent call last):
...
TypeError: rational is not an integer 
```

**Comment by videlec** [comment]
I can not reproduce this. On Sage 8.1.rc3 with gmpy2 and ppl installed I obtain
```
sage: import ppl
sage: ppl.Linear_Expression((1/2,1),2)
x1+2
```
Which is wrong but not a segfault.

**Comment by videlec** [comment]
This is https://trac.sagemath.org/ticket/22928#comment:78
