### ISSUE TITLE
Consistency problem between setup.py and pypi 0.7 version

### ISSUE THREAD

**Issue by vinklein** [videlec/pplpy#30]
Current `setup.py` define a `'test': TestCommand` and the later use the `tests` directory. 
The problem is that `tests` directory is not included in pypi package.
Should we remove the TestCommand from setup.py or have a pypi package including the `tests` directory.
IMO self tests are a nice feature.

Linked to https://trac.sagemath.org/ticket/23024#comment:71

**Comment by videlec** [comment]
Indeed, the tests directory would better be part of the distribution.

**Comment by videlec** [comment]
fixed in `36a8d1d`
