### ISSUE TITLE
Compilation fails with Python 3

### ISSUE THREAD

**Issue by peterwittek** [videlec/pplpy#5]
The module builds, installs and imports perfectly with Python 2. Building fails with Python 3:

    src/pylong.c:753:32: error: ‘PyLongObject’ has no member named ‘ob_size’
         ((PyLongObject *)__pyx_v_L)->ob_size = (-((PyLongObject *)__pyx_v_L)->ob_size);
                                    ^
    src/pylong.c:753:73: error: ‘PyLongObject’ has no member named ‘ob_size’
         ((PyLongObject *)__pyx_v_L)->ob_size = (-((PyLongObject *)__pyx_v_L)->ob_size);
                                                                             ^
    src/pylong.c: In function ‘__pyx_f_6pylong_mpz_set_pylong’:
    src/pylong.c:966:42: error: ‘PyLongObject’ has no member named ‘ob_size’
       __pyx_t_1 = ((PyLongObject *)__pyx_v_L)->ob_size;
                                              ^
    src/pylong.c:1006:44: error: ‘PyLongObject’ has no member named ‘ob_size’
       __pyx_t_2 = ((((PyLongObject *)__pyx_v_L)->ob_size < 0) != 0);
                                                ^
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

I tried it with Python 3.4.3 and 3.5.1, with the variant on PyPI and the latest git. The result is identical in all cases.

**Comment by videlec** [comment]
Thanks for the report! It should be fixed by the commit 3375da1. Could you tell me if it works for you?

**Comment by peterwittek** [comment]
It works like a charm! Many thanks.
