### ISSUE TITLE
pip install pplpy doesn't work

### ISSUE THREAD

**Issue by ypleong** [videlec/pplpy#6]
I installed the required libraries using `brew install gmp` and `brew install ppl`.

Then, I do `pip install pplpy`, and it doesn't work because it cannot find the `gmp.h` file.

Then, I try `env "CFLAGS=-I/usr/local/Cellar/gmp/6.1.1/include/ -I/usr/local/Cellar/gmp/6.1.1/lib/ -I/usr/local/Cellar/ppl/1.2/include/ -I/usr/local/Cellar/ppl/1.2/lib/" pip install pplpy` , and it found all the `*.h` files.

But, it says that 

```
ld: library not found for -lgmp
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'c++' failed with exit status 1
```

Do you know how to resolves this issue? 

I think it would be helpful to include more details on installing the package itself and the required packages.

**Comment by ypleong** [comment]
Actually, there is a typo in my code. It should be
```env "CFLAGS=-I/usr/local/Cellar/gmp/6.1.1/include/ -L/usr/local/Cellar/gmp/6.1.1/lib/ -I/usr/local/Cellar/ppl/1.2/include/ -L/usr/local/Cellar/ppl/1.2/lib/" pip install pplpy```

I still think that it would be useful to have more details on installing the package itself and the required packages.

**Comment by videlec** [comment]
Hi,

Thanks for your report! With the version of the command in your second comment, did the compilation succeed?

On most operating system, the headers and libraries are installed in standard directories like /usr/include and /usr/lib/ where gcc looks for headers and libraries. brew seems to install everything in the non standard /usr/local/Cellar/NAME_OF_THE_PROGRAM/{include, lib}/. You hence need to tell gcc where to find them... Does your gcc also comes from brew?

You might be able to compile with

    $ export CPATH=/usr/local/Cellar/
    $ export LIBRARY_PATH=/usr/local/Cellar/lib/
    $ pip install pplpy

Could you try? (you might first have to uninstall pplpy)

**Comment by ypleong** [comment]
Sorry. I should be clear on my second post. Fixing the typo allow me to install your package properly.

The reason I was using brew was that apt-get doesn't work on OS X and I could not get the required libraries to install properly using the configure and make procedure.
