### ISSUE TITLE
tests

### ISSUE THREAD

**Issue by videlec** [videlec/pplpy#7]
- [x] implement automatic doctesting using the standard library [doctest](https://docs.python.org/3.6/library/doctest.html).
- [x] Check that all doctests pass on both Python 2 and 3
- [x] Add tests for cython usage of ppl (e.g. inline compilation in unittests)
- [x] Create a test command so that `python setup.py test` runs the tests directly, see for example [this link](https://justin.abrah.ms/python/setuppy_distutils_testing.html)
- [x] setup.py test command launch all test (doctest and cython compilation tests)
- [x] Files generated by local cython compilation test done with the setup.py test command should be temporary

Removed:
- Implement additional tests as [unittest](https://docs.python.org/3.6/library/unittest.html)

**Comment by vinklein** [comment]
Continuous Integration of Doctests and cython usage of pplpy is done : https://travis-ci.org/vinklein/pplpy.
The tested version of python are 2.7, 3.4, 3.5, 3.6

**Comment by vinklein** [comment]
Adding a test command to setup.py is done. commit https://github.com/vinklein/pplpy/commit/3a3c6d6bd027ac6dc4f442e0c38ad70adeb67c54.
The command launch the doctests.
For now i don't think pplpy require unittest and in my opinion we can close this issue.

**Comment by videlec** [comment]
Est-ce qu'on pourrait modifier rundoctests.py en runtests.py pour à la fois tester la doc et la compil Cython? Il faut un point d'entrée unique pour les tests.

**Comment by videlec** [comment]
Et du coup, la commande `test` du setup devrait lancer `runtests.py` plutôt que `rundoctests.py`.

**Comment by vinklein** [comment]
Comme vu par email j'ai simplement modifié la command setup.py pour qu'elle lance également les tests de compilation cytthon

**Comment by videlec** [comment]
Dans la version courante, tu ne testais **pas** l'import des fichiers cython. La commande

    subprocess.call(sys.executable, '-c', '"import testpplpy"')

ne fait que construire la chaîne de caractère "import testpplpy". Ce dont on se fout pas mal. (C'est corrigé dans b974239)

De plus, avec la version courante, la compilation pourrait foirer et les tests pourraient passer quand même (le commit 6b5ea45 fixe le problème).

Je comprends pas ce que tu as fait avec la déclaration du langage c++. Pour les deux tu as déclaré à la fois dans le "cythonize" et le fichier source. Apparemment cython emet un warning si ce n'est pas le cas... A voir si il ne faut pas toujours le mettre dans le fichier ".pyx" explicitement.

Par ailleurs, le test de compilation cython laisse en place des fichiers .cpp, des fichiers .so et un répertoire build/... c'est pas génial. Il vaudrait mieux tout copier dans des répertoires temporaires avant de lancer la compil. Par exemple via [tempfile](https://docs.python.org/3.6/library/tempfile.html). Non?

**Comment by vinklein** [comment]
the command test of setup.py now work in a temp directory. see [5f3d5cc](https://github.com/vinklein/pplpy/commit/5f3d5cc72e4a9f9da0b857dc365dafd4753eab3e).
